### PR TITLE
Add Case Coverage tests for Create Report Definition

### PR DESCRIPTION
**Pull request by davidcui1225**
Signed-off-by: David Cui <davidcui@amazon.com>

### Description
Adds case coverage tests in Cypress and refactor cypress tests.
* Add case coverage for creating on-demand and scheduled definitions
* Extend cypress commands to functions
* Add css selectors when needed in `Report settings` and `Report trigger`
* Update jest snapshots 
* Exclude delivery component tests from jest coverage as it is not used in production

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [x] New functionality includes testing.
  - [x] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by davidcui1225** [comment]
Front-end dashboards CI is failing due to common-utils 1.2 snapshot being unavailable, issue created upstream here https://github.com/opensearch-project/opensearch-build/issues/1261

**Review by anirudha — APPROVED** [review]

**Comment by peternied** [comment]
> Front-end dashboards CI is failing due to common-utils 1.2 snapshot being unavailable, issue created upstream here [opensearch-project/opensearch-build#1261](https://github.com/opensearch-project/opensearch-build/issues/1261)

Can you check if this is resolved? the root cause should be mitigated

**Comment by davidcui1225** [comment]
> > Front-end dashboards CI is failing due to common-utils 1.2 snapshot being unavailable, issue created upstream here [opensearch-project/opensearch-build#1261](https://github.com/opensearch-project/opensearch-build/issues/1261)
> 
> Can you check if this is resolved? the root cause should be mitigated

Sure, re-running CI

**Review by joshuali925 — APPROVED** [review]

**Review by zhongnansu — COMMENTED** [review]
I wonder if there's a way for cypress to attach to a request, and verify at least whether a "create" request is successful(200) or not? From what we have now, I think even the reuqest failed, it can still pass the test, right?

**Comment by davidcui1225** [comment]
> I wonder if there's a way for cypress to attach to a request, and verify at least whether a "create" request is successful(200) or not? From what we have now, I think even the reuqest failed, it can still pass the test, right?

It shouldn't pass the test because if the request fails then there will be an error toast and the UI will not re-direct to the reporting landing page, which will cause the cypress test to fail.

**Pull request merged**
