### PR TITLE
[1.2] Bump reports plugins to 1.2.1

### PR DESCRIPTION
**Pull request by joshuali925**
Signed-off-by: Joshua Li <joshuali925@gmail.com>

### Description
Bump reports plugins to 1.2.1 for opensearch 1.2.1 release

### Issues Resolved
[List any issues this PR will resolve]

### Check List
- [ ] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Review by zhongnansu — APPROVED** [review]

**Review by ps48 — APPROVED** [review]

**Comment by peternied** [comment]
@joshuali925 `E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/n/nss/libnss3-dev_3.49.1-1ubuntu1.5_amd64.deb  404  Not Found [IP: 52.250.76.244 80]` Can you look into this?

**Comment by joshuali925** [comment]
> @joshuali925 `E: Failed to fetch http://security.ubuntu.com/ubuntu/pool/main/n/nss/libnss3-dev_3.49.1-1ubuntu1.5_amd64.deb 404 Not Found [IP: 52.250.76.244 80]` Can you look into this?

This is frontend CI failing, which was fixed in #245 . I did not pick it over because we are only bumping/releasing backend plugin, the frontend CI can be ignored

**Comment by zhongnansu** [comment]
@joshuali925 CI failed. The integ test needs the latest 1.2.1.0 job-scheduler artifacts to be in `test/resources`

**Comment by joshuali925** [comment]
> @joshuali925 CI failed. The integ test needs the latest 1.2.1.0 job-scheduler artifacts to be in `test/resources`

building now

**Review by zhongnansu — DISMISSED** [review]

**Review by ps48 — APPROVED** [review]

**Review by zhongnansu — APPROVED** [review]

**Pull request merged**
