### PR TITLE
Add CI workflow for Java 8

### LINKED ISSUE #230: Default CI Java Version to Java 11, run tests on 8, 14 and 17
Coming from https://github.com/opensearch-project/opensearch-plugins/issues/64, default CI Java version to 11 (LTS), and run tests on 8, 14 and 17.

- [ ] Change the default Java version for CI in GitHub actions from 14/15 to 11 (LTS).
- [ ] Add Java 8, 14 (used before), and 17 (next LTS) to the CI matrix.
- [ ] Document Java versions in DEVELOPER_GUIDE.md.

### PR DESCRIPTION
**Pull request by davidcui1225**
### Description
Add CI workflow to test reports-scheduler with Java 8

### Issues Resolved
#230 

### Check List
- [x] New functionality includes testing.
  - [ ] All tests pass, including unit test, integration test and doctest
- [ ] New functionality has been documented.
  - [ ] New functionality has javadoc added
  - [ ] New functionality has user manual doc added
- [ x] Commits are signed per the DCO using --signoff

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.
For more information on following Developer Certificate of Origin and signing off your commits, please check [here](https://github.com/opensearch-project/OpenSearch/blob/main/CONTRIBUTING.md#developer-certificate-of-origin).

### CODE REVIEW

**Comment by dblock** [comment]
Did you try building and testing on 8?

**Comment by davidcui1225** [comment]
> Did you try building and testing on 8? That would be preferred than building on 11 then testing on 11 unless it's too much work.

When I build on 8 I get the following error on `compileKotlin`:

```
e: /Users/davidcui/dashboards-reports/reports-scheduler/src/main/kotlin/org/opensearch/reportsscheduler/settings/PluginSettings.kt: (98, 46): Unresolved reference: of
```

That is referencing this line:
```
val defaultSettingYmlFile = Path.of(configDirName, PLUGIN_NAME, "reports-scheduler.yml")
```

I can debug but wanted to get a working version posted first

**Comment by joshuali925** [comment]
@davidcui1225 https://github.com/opensearch-project/OpenSearch/issues/1591#issuecomment-977200180

**Comment by davidcui1225** [comment]
> @davidcui1225 [opensearch-project/OpenSearch#1591 (comment)](https://github.com/opensearch-project/OpenSearch/issues/1591#issuecomment-977200180)

From what I'm reading here l don't see an explicit solution for this issue yet? Is the current strategy of building with 11 and testing against 8 an acceptable workaround for the time being then?

**Comment by davidcui1225** [comment]
> > @davidcui1225 [opensearch-project/OpenSearch#1591 (comment)](https://github.com/opensearch-project/OpenSearch/issues/1591#issuecomment-977200180)
> 
> From what I'm reading here l don't see an explicit solution for this issue yet? Is the current strategy of building with 11 and testing against 8 an acceptable workaround for the time being then?

@dblock ?

**Comment by davidcui1225** [comment]
Testing with JDK 8 against `integTest` has the same issue as building with JDK 8, with `NoSuchMethodError` on `Path.of`.

**Comment by davidcui1225** [comment]
Closing for #304

**Pull request closed without merging**
